---

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

- name: install rabbitmq-server dependencies (RedHat)
  yum: 
   name: "{{ item }}" 
   state: present
  with_items:
    - erlang
    - libselinux-python

#- name: install rabbitmq-server (RedHat)
#  yum: 
#   name: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.15/rabbitmq-server-3.6.15-1.el7.noarch.rpm 
#   state: present


- name: install rabbitmq rpm from a local file
  yum:
    name: "{{ local_rabbit_rpm }}"
    state: present

#- name: enable rabbitmq-server to survive reboot
#  service: 
#  name: rabbitmq-server 
#  enabled: yes

- name: Ensure rabbitmq is started and enabled (if configured).
  service:
    name: "{{ rabbitmq_daemon }}"
    state: "{{ rabbitmq_state }}"
    enabled: "{{ rabbitmq_enabled }}"

- name: customize logrotate rules
  template:
    src: etc/logrotate.d/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644
