---
# Setup installation repositories/ requied dependencies

#- name: Add GPG key.
#  rpm_key:
#    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
#    state: present

- name: install the epel-release 
  yum: 
   name: epel-release
   state: latest 

- name: Ensure erlang is installed.
  package:
    name: erlang
    state: present

#- name: add rabbitmq repository
#  yum:
#    name: https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.7.7/rabbitmq-server-3.7.7-1.el7.noarch.rpm
#    update_cache: yes
#    state: present

